# Generated by Django 4.0.2 on 2022-10-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('options', models.CharField(max_length=300)),
                ('name1', models.CharField(max_length=300)),
                ('name2', models.CharField(max_length=300)),
                ('name3', models.CharField(max_length=300)),
                ('name4', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SampleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('options', models.CharField(max_length=300)),
                ('name1', models.CharField(max_length=300)),
                ('name2', models.CharField(max_length=300)),
                ('name3', models.CharField(max_length=300)),
                ('name4', models.CharField(max_length=300)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='api.sample')),
            ],
        ),
    ]
