# Generated by Django 4.0.2 on 2022-10-24 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('fieldsOfExpertise', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientStatusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('jobValuation', models.FloatField(blank=True, null=True)),
                ('taskCode', models.CharField(blank=True, max_length=50, null=True)),
                ('permitNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('BPRfee', models.CharField(blank=True, max_length=50, null=True)),
                ('clientfee', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('expeditionStatus', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReceived', models.DateField(blank=True, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('dateOut', models.DateField(blank=True, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('billingStatus', models.BooleanField(blank=True, null=True)),
                ('completionStatus', models.BooleanField(blank=True, null=True)),
                ('evaluation', models.FloatField(blank=True, null=True)),
                ('feeType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cycle_Fee_Type', to='jobs.feetype')),
                ('jobID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='JobInfo', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobCycleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobScopeOfReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KidOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PlanReviewDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SampleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('submittalType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.submittaltype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('clientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.client')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.projectstatuslist')),
            ],
        ),
        migrations.CreateModel(
            name='POC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.client')),
            ],
        ),
        migrations.CreateModel(
            name='PlanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('completionStatus', models.BooleanField(blank=True, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.planreviewdiscipline')),
                ('jobcycleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plan_reviews', to='jobs.jobcycle')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plan_reviewer', to='jobs.agent')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobstatuslist')),
            ],
        ),
        migrations.AddField(
            model_name='jobcycle',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobstatuslist'),
        ),
        migrations.AddField(
            model_name='jobcycle',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Job_Cycle_Type', to='jobs.jobcycletype'),
        ),
        migrations.AddField(
            model_name='job',
            name='JobType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobtype'),
        ),
        migrations.AddField(
            model_name='job',
            name='POC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.poc'),
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.client'),
        ),
        migrations.AddField(
            model_name='job',
            name='feeType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Fee_Type', to='jobs.feetype'),
        ),
        migrations.AddField(
            model_name='job',
            name='projectID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.project'),
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.region'),
        ),
        migrations.AddField(
            model_name='job',
            name='relatedProject',
            field=models.ManyToManyField(blank=True, related_name='RelatedProject', to='jobs.Project'),
        ),
        migrations.AddField(
            model_name='job',
            name='scopeofreview',
            field=models.ManyToManyField(blank=True, related_name='scopeofreview', to='jobs.JobScopeOfReview'),
        ),
        migrations.AddField(
            model_name='client',
            name='regionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.region'),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.clienttype'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('allowableArea', models.FloatField()),
                ('height', models.FloatField()),
                ('use', models.CharField(max_length=50)),
                ('stories', models.CharField(max_length=50)),
                ('highRise', models.BooleanField()),
                ('autosprinkler', models.BooleanField()),
                ('coverage', models.BooleanField()),
                ('otherBuilding', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('jobID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.userprofile'),
        ),
    ]
