# Generated by Django 4.0.2 on 2022-10-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobcycle_delivered_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcycle',
            old_name='delivered_by',
            new_name='deliveredBy',
        ),
    ]
